package:
  name: morphemes
  version: 1.0.8

source:
  git_rev: v1.0.8
  git_url: https://github.com/ecscstatsconsulting/morphemes.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - python
    - setuptools
    - requests
    - pandas
    - tinydb

about:
  home: https://github.com/ecscstatsconsulting/morphemes