{% set version = "1.0.8" %}
#CURRENTLY DOES NOT WORK BECAUSE OF tinydb IS ONLY AVAILABLE ON CONDA FORGE CHANNEL
package:
  name: morphemes
  version: {{ version }}

source:
  git_url: https://github.com/ecscstatsconsulting/morphemes.git
  git_rev: v1.0.8

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - requests
    - pandas
  run:
    - python

test:
  imports:
    - morphemes

about:
  home: https://github.com/shibukawa/imagesize_py
  license: MIT
  summary: 'A practical Python Library for identifying morphemes in the english language.'
  description: |
    A practical Python Library for identifying morphemes in the english language.
  dev_url: https://github.com/ecscstatsconsulting/morphemes
  doc_url: https://github.com/ecscstatsconsulting/morphemes#readme
  doc_source_url: https://github.com/ecscstatsconsulting/morphemes/blob/main/README.md